{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.funczz",
    "module": "fsm",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fsm-0.1.0.jar",
          "url": "fsm-0.1.0.jar",
          "size": 9287,
          "sha512": "165f9fc01749b70886e82a0aaff67e2ade1f1da97ab3213461891e9a5cc310540be8eac3af102ac31048843622dc5d09b701416a5e0a6192a73ee97a4ef0f210",
          "sha256": "3c6978517e4da334759a3597f61ede5f71a43c6c568a9166e8c8148f14931c05",
          "sha1": "7d8d68c7708c053dfe19542b323fd7e7b0cf5575",
          "md5": "ba2b1569adda2b9e9c9882d39cd72028"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "fsm-0.1.0.jar",
          "url": "fsm-0.1.0.jar",
          "size": 9287,
          "sha512": "165f9fc01749b70886e82a0aaff67e2ade1f1da97ab3213461891e9a5cc310540be8eac3af102ac31048843622dc5d09b701416a5e0a6192a73ee97a4ef0f210",
          "sha256": "3c6978517e4da334759a3597f61ede5f71a43c6c568a9166e8c8148f14931c05",
          "sha1": "7d8d68c7708c053dfe19542b323fd7e7b0cf5575",
          "md5": "ba2b1569adda2b9e9c9882d39cd72028"
        }
      ]
    }
  ]
}
