{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.funczz",
    "module": "kotlin-fsm-interface",
    "version": "1.0.0-rc.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "6yjl4td3ybawxbptr7apmi7mhu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-fsm-interface-1.0.0-rc.1.jar",
          "url": "kotlin-fsm-interface-1.0.0-rc.1.jar",
          "size": 3615,
          "sha512": "b96c6785b7ff1f627dc396150c57033de23037b82fcfac8318578df26fea99067c803f1fb70e21f13ffa28c6e8da6985a6f1804915cc9b12b00018632df67dcd",
          "sha256": "548561f2ddde9a22d37147adb9ac5e0b0e8b65f76e85eec9930c74599d3e8f75",
          "sha1": "17bd80170371824b25eed87642d178354b0ff78c",
          "md5": "7702ad56a4265be08a921c472d0fd3b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-fsm-interface-1.0.0-rc.1.jar",
          "url": "kotlin-fsm-interface-1.0.0-rc.1.jar",
          "size": 3615,
          "sha512": "b96c6785b7ff1f627dc396150c57033de23037b82fcfac8318578df26fea99067c803f1fb70e21f13ffa28c6e8da6985a6f1804915cc9b12b00018632df67dcd",
          "sha256": "548561f2ddde9a22d37147adb9ac5e0b0e8b65f76e85eec9930c74599d3e8f75",
          "sha1": "17bd80170371824b25eed87642d178354b0ff78c",
          "md5": "7702ad56a4265be08a921c472d0fd3b5"
        }
      ]
    }
  ]
}
